services:
  fieldly-app:
    build:
      context: .
      dockerfile: Dockerfile

      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}

    container_name: fieldly-app-dev

    command: pnpm dev
    
    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true

    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16

    container_name: fieldly-postgres-dev

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fieldly

    ports:
      - "5432:5432"

    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: fieldly-redis-dev

    ports:
      - "6379:6379"

volumes:
  postgres_data_dev: